PROBABILISTIC_INFERENCE:
    # One of the following: 'standard_nms', 'mc_dropout_ensembles',
    # 'anchor_statistics', 'bayes_od', 'ensemble'
    INFERENCE_MODE: 'bayes_od'
    AFFINITY_THRESHOLD: 0.9

    BAYES_OD:
        CLS_MERGE_MODE: 'max_score'  # 'bayesian_inference' or 'max_score'
        # 'bayesian_inference' or 'covariance_intersection'
        BOX_MERGE_MODE: 'bayesian_inference'

MODEL:
    WEIGHTS: "/home/submodules/pod_compare/data/BDD-Detection/retinanet/retinanet_R_50_FPN_1x_reg_cls_var/random_seed_0/model_0059999.pth"
